name: payback
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A
  awesome_dialog: 2.1.1

  # C
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.2.0
  carousel_slider: 4.0.0
  cpf_cnpj_validator: ^2.0.0

  # D
  dio: 4.0.0
  device_info: 2.0.2
  datetime_picker_formfield: ^2.0.0

  # E
  encrypt: 5.0.1

  # F
  flutter_modular: ^4.3.0
  flutter_mobx: ^2.0.2
  flutter_svg: ^1.0.0
  flutter_i18n: 0.30.0
  flutter_swiper: 1.1.6

  # G
  google_fonts: 2.1.0

  # I
  image_picker: ^0.8.4+2
  internet_connection_checker: ^0.0.1+3

  # M
  mobx: ^2.0.5
  mask_text_input_formatter: ^2.0.0

  # P
  path_provider: ^2.0.8

  # S
  shared_preferences: 2.0.6
  share: 2.0.4

  # U
  uuid: 3.0.4
  url_launcher: 6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # B
  build_runner: ^2.1.5

  # F
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.1

  # J
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1

  # M
  mobx_codegen: ^2.0.4
  modular_test: ^1.0.1+1

flutter_native_splash:
  image: assets/icon/splash_art/logo_splash.svg
  color: "474797"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/icon/login/
    - assets/icon/load/
    - assets/icon/splash_art/
    - assets/i18n/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
scripts:
  #comando para rodar os scripts ' slidy run NomeScript
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  mobxWatch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  mobxBuild: flutter packages pub run build_runner build --delete-conflicting-outputs

#flutter pub run flutter_launcher_icons:main - comando para gerar icon
#flutter pub pub run flutter_native_splash:create - comando para gerar splashArt
#flutter pub run flutter_i18n validate - Este comando é usado para validar todos os arquivos de tradução dentro do projeto
#flutter pub run flutter_i18n diff en.yaml it.json - Este comando é usado para encontrar as diferenças entre as chaves dos arquivos de tradução desejados
